name: Deploy Toyooran

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/Toyooran

            git pull origin main

            docker build -t toyooran .

            docker stop toyooran-app || true
            docker rm toyooran-app || true

            docker run -d \
              --name toyooran-app \
              -p 3000:3000 \
              --restart always \
              toyooran